// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using testnetapp.Data;

namespace testnetapp.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190208093604_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("testnetapp.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("testnetapp.Data.Models.BookTag", b =>
                {
                    b.Property<int>("BookId");

                    b.Property<int>("TagId");

                    b.Property<int?>("TagId1");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("TagId1");

                    b.ToTable("BookTag");
                });

            modelBuilder.Entity("testnetapp.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("testnetapp.Data.Models.BookTag", b =>
                {
                    b.HasOne("testnetapp.Data.Models.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("testnetapp.Data.Models.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId1");
                });
#pragma warning restore 612, 618
        }
    }
}
